users:
  - name: admin
    password: admin
    admin: true
    publish: ["#"]
    subscribe: ["#"]
  - name: pub
    password: pub
    publish: ["hello", "demo/#"]
    subscribe: []
  - name: sub
    password: sub
    publish: []
    subscribe: ["hello", "demo/#"]
